services:
  # -------------------
  # Django Backend
  # -------------------
  - type: web
    name: traveller-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn travelplanner.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: travelplanner.settings
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 3

    # This ensures the correct working directory
    rootDir: backend

  # -------------------
  # React Frontend
  # -------------------
  - type: web
    name: traveller-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://traveller-backend.onrender.com
